# Welcome to Jekyll!

# Website settings
title: ILR+G 2025
description: The Official Site of ICCV 2025 Workshop, Instance-Level Recognition and Generation Workshop
keywords: instance-level recognition, instance-level generation, large-scale recognition, particular objects, particular events
baseurl:  # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://ilr-workshop.github.io/ICCVW2025/  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /ilr-workshop/ICCVW2025/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: ILR+G 2025   # Be used at blog posts' author.
  first_name:   # Be used at index page about me section.
  last_name: ILR+G 2025  # Be used at index page about me section.
  #avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  #github_username: jarrekk  # Leave blank if you don't have now
  #linkedin_id: jarrekk # Leave blank if you don't have now
  #facebook_username: jiakunnj  # Leave blank if you don't have now
  #twitter_username: jiakun614  # Leave blank if you don't have now
  email: ilr-workshop@googlegroups.com  # Leave blank if you don't have now
  #cv: http://cv.jarrekk.com  # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  desc: >
    <p>The main focus of our workshop is on computer vision tasks that operate at instance-level, including both recognition (instance-level recognition - ILR) and generation (instance-level generation - ILG), denoted as ILR+G. More precisely, ILR+G is the task of identifying, comparing, and generating images of specific objects, scenes, or events. </p><p>This year, we expand the scope of our workshop to ILG and the potential synergy between ILG and ILR. We will organize a call for papers, and host keynote talks by renowned speakers and invited paper talks from the main conference.</p><p>The 2025 Instance-Level Recognition and Generation (ILR+G) Workshop is a follow-up of six successful editions of our previous workshops &mdash; the first two having focused only on landmark recognition (<a href="https://landmarksworkshop.github.io/CVPRW2018" target="_blank"><span class="navy">CVPRW18</span></a>, <a href="https://landmarksworkshop.github.io/CVPRW2019" target="_blank"><span class="navy">CVPRW19</span></a>), the following ones expanding to the domains of artworks and products (<a href="https://ilr-workshop.github.io/ECCVW2020/" target="_blank"><span class="navy">ECCVW20</span></a>, <a href="https://ilr-workshop.github.io/ICCVW2021/" target="_blank"><span class="navy">ICCVW21</span></a>), introducing the universal image embedding problem (<a href="https://ilr-workshop.github.io/ECCVW2022/" target="_blank"><span class="navy">ECCVW22</span></a>, and the latest ones introducing a call for papers (<a href="https://ilr-workshop.github.io/ECCVW2024/" target="_blank"><span class="navy">ECCVW24</span></a>).</p>
# comment
  disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: ILR+G 2025

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: on  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


theme: jekyll-theme-cayman
